name: manage-azure-policy-1479a449
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Log_Analytics_workspace_1f6e93e8-6b31-41b1-83f6-36e449a42579/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_237e0f7e-b0e8-4ec4-ad46-8c12cb66d673/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Storage_Gen1_to_Log_Analytics_workspace_25763a0a-5783-4f14-969e-79d4933eb74b/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Event_Hub_3d5da587-71bd-41f5-ac95-dd3330c2d58d/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Event_Hub_4daddf25-4823-43d4-88eb-2419eb6dcc08/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Event_Hub_6b51af03-9277-49a9-a3f8-1c69c9ff7403/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_SQL_Database_to_Event_Hub_9a7c7a7d-49e5-4213-bea8-6a502b6272e0/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Event_Hub_a1dae6c7-13f3-48ea-a149-ff8442661f60/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Recovery_Services_Vault_to_Log_Analytics_workspace_for_resource_specific_categories._c717fb0c-d118-4c43-ab3d-ece30ac81fb3/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Log_Analytics_workspace_c84e5349-db6d-4769-805e-e14037dab9b5/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_c9c29499-c1d1-4195-99bd-2ec9e3a9dc89/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Event_Hub_db51110f-0865-4a6e-b274-e2e07a5b2cd7/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Storage_Gen1_to_Event_Hub_e8d096bc-85de-4c5f-8cfb-857bd1b9d62d/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Event_Hub_ed7c8c13-51e7-49d1-8a43-8490431a0da2/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Event_Hub_edf3780c-3d70-40fe-b17e-ab72013dafca/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Event_Hub_ef7b61ef-b8e4-4c91-8e78-6946c6b0023f/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Automation_to_Log_Analytics_workspace_Deploy-Diagnostics-AA/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_API_for_FHIR_to_Log_Analytics_workspace_Deploy-Diagnostics-ApiForFHIR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_CDN_Endpoint_to_Log_Analytics_workspace_Deploy-Diagnostics-CDNEndpoints/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Cognitive_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-CognitiveServices/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Cosmos_DB_to_Log_Analytics_workspace_Deploy-Diagnostics-CosmosDB/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Databricks_to_Log_Analytics_workspace_Deploy-Diagnostics-Databricks/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Data_Explorer_Cluster_to_Log_Analytics_workspace_Deploy-Diagnostics-DataExplorerCluster/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Factory_to_Log_Analytics_workspace_Deploy-Diagnostics-DataFactory/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_subscriptions_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_System_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSystemTopic/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Event_Grid_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridTopic/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Front_Door_to_Log_Analytics_workspace_Deploy-Diagnostics-FrontDoor/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_HDInsight_to_Log_Analytics_workspace_Deploy-Diagnostics-HDInsight/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_integration_service_environment_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsISE/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_MariaDB_to_Log_Analytics_workspace_Deploy-Diagnostics-MariaDB/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Azure_Media_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-MediaService/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Machine_Learning_workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-MlWorkspace/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Database_for_MySQL_to_Log_Analytics_workspace_Deploy-Diagnostics-MySQL/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Database_for_PostgreSQL_to_Log_Analytics_workspace_Deploy-Diagnostics-PostgreSQL/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Power_BI_Embedded_to_Log_Analytics_workspace_Deploy-Diagnostics-PowerBIEmbedded/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Redis_Cache_to_Log_Analytics_workspace_Deploy-Diagnostics-RedisCache/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Relay_to_Log_Analytics_workspace_Deploy-Diagnostics-Relay/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SignalR_to_Log_Analytics_workspace_Deploy-Diagnostics-SignalR/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SQL_Elastic_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLElasticPools/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_SQL_Managed_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLMI/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Time_Series_Insights_to_Log_Analytics_workspace_Deploy-Diagnostics-TimeSeriesInsights/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Application_group_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDAppGroup/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Host_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDHostPools/**'
#      - 'policies/Deploy_Diagnostic_Settings_for_WVD_Workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDWorkspace/**'
#      - .github/workflows/manage-azure-policy-1479a449.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_1479a449}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/Deploy_Diagnostic_Settings_to_Azure_Services_Deploy-Diagnostics-LogAnalytics/**
          policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**
          policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**
          policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Log_Analytics_workspace_1f6e93e8-6b31-41b1-83f6-36e449a42579/**
          policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Log_Analytics_workspace_237e0f7e-b0e8-4ec4-ad46-8c12cb66d673/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Storage_Gen1_to_Log_Analytics_workspace_25763a0a-5783-4f14-969e-79d4933eb74b/**
          policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Event_Hub_3d5da587-71bd-41f5-ac95-dd3330c2d58d/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Event_Hub_4daddf25-4823-43d4-88eb-2419eb6dcc08/**
          policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Event_Hub_6b51af03-9277-49a9-a3f8-1c69c9ff7403/**
          policies/Deploy_Diagnostic_Settings_for_Azure_SQL_Database_to_Event_Hub_9a7c7a7d-49e5-4213-bea8-6a502b6272e0/**
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Event_Hub_a1dae6c7-13f3-48ea-a149-ff8442661f60/**
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**
          policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Log_Analytics_workspace_bef3f64c-5290-43b7-85b0-9b254eef4c47/**
          policies/Deploy_Diagnostic_Settings_for_Recovery_Services_Vault_to_Log_Analytics_workspace_for_resource_specific_categories._c717fb0c-d118-4c43-ab3d-ece30ac81fb3/**
          policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Log_Analytics_workspace_c84e5349-db6d-4769-805e-e14037dab9b5/**
          policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_c9c29499-c1d1-4195-99bd-2ec9e3a9dc89/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_d56a5a7c-72d7-42bc-8ceb-3baf4c0eae03/**
          policies/Deploy_Diagnostic_Settings_for_Batch_Account_to_Event_Hub_db51110f-0865-4a6e-b274-e2e07a5b2cd7/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Storage_Gen1_to_Event_Hub_e8d096bc-85de-4c5f-8cfb-857bd1b9d62d/**
          policies/Deploy_Diagnostic_Settings_for_Key_Vault_to_Event_Hub_ed7c8c13-51e7-49d1-8a43-8490431a0da2/**
          policies/Deploy_Diagnostic_Settings_for_Stream_Analytics_to_Event_Hub_edf3780c-3d70-40fe-b17e-ab72013dafca/**
          policies/Deploy_Diagnostic_Settings_for_Event_Hub_to_Event_Hub_ef7b61ef-b8e4-4c91-8e78-6946c6b0023f/**
          policies/Deploy_Diagnostic_Settings_for_Automation_to_Log_Analytics_workspace_Deploy-Diagnostics-AA/**
          policies/Deploy_Diagnostic_Settings_for_Container_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-ACI/**
          policies/Deploy_Diagnostic_Settings_for_Container_Registry_to_Log_Analytics_workspace_Deploy-Diagnostics-ACR/**
          policies/Deploy_Diagnostic_Settings_for_Analysis_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-AnalysisService/**
          policies/Deploy_Diagnostic_Settings_for_Azure_API_for_FHIR_to_Log_Analytics_workspace_Deploy-Diagnostics-ApiForFHIR/**
          policies/Deploy_Diagnostic_Settings_for_API_Management_to_Log_Analytics_workspace_Deploy-Diagnostics-APIMgmt/**
          policies/Deploy_Diagnostic_Settings_for_Application_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-ApplicationGateway/**
          policies/Deploy_Diagnostic_Settings_for_CDN_Endpoint_to_Log_Analytics_workspace_Deploy-Diagnostics-CDNEndpoints/**
          policies/Deploy_Diagnostic_Settings_for_Cognitive_Services_to_Log_Analytics_workspace_Deploy-Diagnostics-CognitiveServices/**
          policies/Deploy_Diagnostic_Settings_for_Cosmos_DB_to_Log_Analytics_workspace_Deploy-Diagnostics-CosmosDB/**
          policies/Deploy_Diagnostic_Settings_for_Databricks_to_Log_Analytics_workspace_Deploy-Diagnostics-Databricks/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Data_Explorer_Cluster_to_Log_Analytics_workspace_Deploy-Diagnostics-DataExplorerCluster/**
          policies/Deploy_Diagnostic_Settings_for_Data_Factory_to_Log_Analytics_workspace_Deploy-Diagnostics-DataFactory/**
          policies/Deploy_Diagnostic_Settings_for_Data_Lake_Analytics_to_Log_Analytics_workspace_Deploy-Diagnostics-DLAnalytics/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_subscriptions_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSub/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_System_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridSystemTopic/**
          policies/Deploy_Diagnostic_Settings_for_Event_Grid_Topic_to_Log_Analytics_workspace_Deploy-Diagnostics-EventGridTopic/**
          policies/Deploy_Diagnostic_Settings_for_ExpressRoute_to_Log_Analytics_workspace_Deploy-Diagnostics-ExpressRoute/**
          policies/Deploy_Diagnostic_Settings_for_Firewall_to_Log_Analytics_workspace_Deploy-Diagnostics-Firewall/**
          policies/Deploy_Diagnostic_Settings_for_Front_Door_to_Log_Analytics_workspace_Deploy-Diagnostics-FrontDoor/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Function_App_to_Log_Analytics_workspace_Deploy-Diagnostics-Function/**
          policies/Deploy_Diagnostic_Settings_for_HDInsight_to_Log_Analytics_workspace_Deploy-Diagnostics-HDInsight/**
          policies/Deploy_Diagnostic_Settings_for_IoT_Hub_to_Log_Analytics_workspace_Deploy-Diagnostics-iotHub/**
          policies/Deploy_Diagnostic_Settings_for_Load_Balancer_to_Log_Analytics_workspace_Deploy-Diagnostics-LoadBalancer/**
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_integration_service_environment_to_Log_Analytics_workspace_Deploy-Diagnostics-LogicAppsISE/**
          policies/Deploy_Diagnostic_Settings_for_MariaDB_to_Log_Analytics_workspace_Deploy-Diagnostics-MariaDB/**
          policies/Deploy_Diagnostic_Settings_for_Azure_Media_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-MediaService/**
          policies/Deploy_Diagnostic_Settings_for_Machine_Learning_workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-MlWorkspace/**
          policies/Deploy_Diagnostic_Settings_for_Database_for_MySQL_to_Log_Analytics_workspace_Deploy-Diagnostics-MySQL/**
          policies/Deploy_Diagnostic_Settings_for_Network_Security_Groups_to_Log_Analytics_workspace_Deploy-Diagnostics-NetworkSecurityGroups/**
          policies/Deploy_Diagnostic_Settings_for_Network_Interfaces_to_Log_Analytics_workspace_Deploy-Diagnostics-NIC/**
          policies/Deploy_Diagnostic_Settings_for_Database_for_PostgreSQL_to_Log_Analytics_workspace_Deploy-Diagnostics-PostgreSQL/**
          policies/Deploy_Diagnostic_Settings_for_Power_BI_Embedded_to_Log_Analytics_workspace_Deploy-Diagnostics-PowerBIEmbedded/**
          policies/Deploy_Diagnostic_Settings_for_Redis_Cache_to_Log_Analytics_workspace_Deploy-Diagnostics-RedisCache/**
          policies/Deploy_Diagnostic_Settings_for_Relay_to_Log_Analytics_workspace_Deploy-Diagnostics-Relay/**
          policies/Deploy_Diagnostic_Settings_for_SignalR_to_Log_Analytics_workspace_Deploy-Diagnostics-SignalR/**
          policies/Deploy_Diagnostic_Settings_for_SQL_Elastic_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLElasticPools/**
          policies/Deploy_Diagnostic_Settings_for_SQL_Managed_Instances_to_Log_Analytics_workspace_Deploy-Diagnostics-SQLMI/**
          policies/Deploy_Diagnostic_Settings_for_Time_Series_Insights_to_Log_Analytics_workspace_Deploy-Diagnostics-TimeSeriesInsights/**
          policies/Deploy_Diagnostic_Settings_for_Traffic_Manager_to_Log_Analytics_workspace_Deploy-Diagnostics-TrafficManager/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Network_to_Log_Analytics_workspace_Deploy-Diagnostics-VirtualNetwork/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machines_to_Log_Analytics_workspace_Deploy-Diagnostics-VM/**
          policies/Deploy_Diagnostic_Settings_for_Virtual_Machine_Scale_Sets_to_Log_Analytics_workspace_Deploy-Diagnostics-VMSS/**
          policies/Deploy_Diagnostic_Settings_for_VPN_Gateway_to_Log_Analytics_workspace_Deploy-Diagnostics-VNetGW/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_Plan_to_Log_Analytics_workspace_Deploy-Diagnostics-WebServerFarm/**
          policies/Deploy_Diagnostic_Settings_for_App_Service_to_Log_Analytics_workspace_Deploy-Diagnostics-Website/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Application_group_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDAppGroup/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Host_Pools_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDHostPools/**
          policies/Deploy_Diagnostic_Settings_for_WVD_Workspace_to_Log_Analytics_workspace_Deploy-Diagnostics-WVDWorkspace/**
